// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GCM_Sakoe_cpp
List GCM_Sakoe_cpp(Rcpp::NumericMatrix cM, int ws);
RcppExport SEXP IncDTW_GCM_Sakoe_cpp(SEXP cMSEXP, SEXP wsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cM(cMSEXP);
    Rcpp::traits::input_parameter< int >::type ws(wsSEXP);
    rcpp_result_gen = Rcpp::wrap(GCM_Sakoe_cpp(cM, ws));
    return rcpp_result_gen;
END_RCPP
}
// IGCM_Sakoe_cpp
List IGCM_Sakoe_cpp(Rcpp::NumericMatrix gcmN, Rcpp::NumericMatrix dmN, Rcpp::NumericMatrix cmN, int ws);
RcppExport SEXP IncDTW_IGCM_Sakoe_cpp(SEXP gcmNSEXP, SEXP dmNSEXP, SEXP cmNSEXP, SEXP wsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gcmN(gcmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dmN(dmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cmN(cmNSEXP);
    Rcpp::traits::input_parameter< int >::type ws(wsSEXP);
    rcpp_result_gen = Rcpp::wrap(IGCM_Sakoe_cpp(gcmN, dmN, cmN, ws));
    return rcpp_result_gen;
END_RCPP
}
// GCM_cpp
List GCM_cpp(Rcpp::NumericMatrix cM);
RcppExport SEXP IncDTW_GCM_cpp(SEXP cMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cM(cMSEXP);
    rcpp_result_gen = Rcpp::wrap(GCM_cpp(cM));
    return rcpp_result_gen;
END_RCPP
}
// IGCM_cpp
List IGCM_cpp(Rcpp::NumericMatrix gcmN, Rcpp::NumericMatrix dmN, Rcpp::NumericMatrix cmN);
RcppExport SEXP IncDTW_IGCM_cpp(SEXP gcmNSEXP, SEXP dmNSEXP, SEXP cmNSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gcmN(gcmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dmN(dmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cmN(cmNSEXP);
    rcpp_result_gen = Rcpp::wrap(IGCM_cpp(gcmN, dmN, cmN));
    return rcpp_result_gen;
END_RCPP
}
// BACKTRACK_cpp
List BACKTRACK_cpp(Rcpp::NumericMatrix dm);
RcppExport SEXP IncDTW_BACKTRACK_cpp(SEXP dmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type dm(dmSEXP);
    rcpp_result_gen = Rcpp::wrap(BACKTRACK_cpp(dm));
    return rcpp_result_gen;
END_RCPP
}
