// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cpp_dtw2vec
double cpp_dtw2vec(NumericVector x, NumericVector y);
RcppExport SEXP _IncDTW_cpp_dtw2vec(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dtw2vec(x, y));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dtw2vec_inc
List cpp_dtw2vec_inc(NumericVector x, NumericVector newObs, NumericVector gcm_lc);
RcppExport SEXP _IncDTW_cpp_dtw2vec_inc(SEXP xSEXP, SEXP newObsSEXP, SEXP gcm_lcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type newObs(newObsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcm_lc(gcm_lcSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dtw2vec_inc(x, newObs, gcm_lc));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dtw2vec_inc_ws
List cpp_dtw2vec_inc_ws(NumericVector x, NumericVector newObs, NumericVector gcm_lc, int ws, int ny);
RcppExport SEXP _IncDTW_cpp_dtw2vec_inc_ws(SEXP xSEXP, SEXP newObsSEXP, SEXP gcm_lcSEXP, SEXP wsSEXP, SEXP nySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type newObs(newObsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gcm_lc(gcm_lcSEXP);
    Rcpp::traits::input_parameter< int >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< int >::type ny(nySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dtw2vec_inc_ws(x, newObs, gcm_lc, ws, ny));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dtw2vec_ws
double cpp_dtw2vec_ws(NumericVector x, NumericVector y, int ws);
RcppExport SEXP _IncDTW_cpp_dtw2vec_ws(SEXP xSEXP, SEXP ySEXP, SEXP wsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type ws(wsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dtw2vec_ws(x, y, ws));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dtw2vec_ea
double cpp_dtw2vec_ea(NumericVector x, NumericVector y, double threshold);
RcppExport SEXP _IncDTW_cpp_dtw2vec_ea(SEXP xSEXP, SEXP ySEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dtw2vec_ea(x, y, threshold));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dtw2vec_ws_ea
double cpp_dtw2vec_ws_ea(NumericVector x, NumericVector y, int ws, double threshold);
RcppExport SEXP _IncDTW_cpp_dtw2vec_ws_ea(SEXP xSEXP, SEXP ySEXP, SEXP wsSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dtw2vec_ws_ea(x, y, ws, threshold));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dtw2vec_v32
double cpp_dtw2vec_v32(NumericVector x, NumericVector y);
RcppExport SEXP _IncDTW_cpp_dtw2vec_v32(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dtw2vec_v32(x, y));
    return rcpp_result_gen;
END_RCPP
}
// GCM_Sakoe_cpp
List GCM_Sakoe_cpp(Rcpp::NumericMatrix cM, int ws);
RcppExport SEXP _IncDTW_GCM_Sakoe_cpp(SEXP cMSEXP, SEXP wsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cM(cMSEXP);
    Rcpp::traits::input_parameter< int >::type ws(wsSEXP);
    rcpp_result_gen = Rcpp::wrap(GCM_Sakoe_cpp(cM, ws));
    return rcpp_result_gen;
END_RCPP
}
// IGCM_Sakoe_cpp
List IGCM_Sakoe_cpp(Rcpp::NumericMatrix gcmN, Rcpp::IntegerMatrix dmN, Rcpp::NumericMatrix cmN, int ws);
RcppExport SEXP _IncDTW_IGCM_Sakoe_cpp(SEXP gcmNSEXP, SEXP dmNSEXP, SEXP cmNSEXP, SEXP wsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gcmN(gcmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dmN(dmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cmN(cmNSEXP);
    Rcpp::traits::input_parameter< int >::type ws(wsSEXP);
    rcpp_result_gen = Rcpp::wrap(IGCM_Sakoe_cpp(gcmN, dmN, cmN, ws));
    return rcpp_result_gen;
END_RCPP
}
// GCM_cpp
List GCM_cpp(Rcpp::NumericMatrix cM);
RcppExport SEXP _IncDTW_GCM_cpp(SEXP cMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cM(cMSEXP);
    rcpp_result_gen = Rcpp::wrap(GCM_cpp(cM));
    return rcpp_result_gen;
END_RCPP
}
// IGCM_cpp
List IGCM_cpp(Rcpp::NumericMatrix gcmN, Rcpp::IntegerMatrix dmN, Rcpp::NumericMatrix cmN);
RcppExport SEXP _IncDTW_IGCM_cpp(SEXP gcmNSEXP, SEXP dmNSEXP, SEXP cmNSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gcmN(gcmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dmN(dmNSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cmN(cmNSEXP);
    rcpp_result_gen = Rcpp::wrap(IGCM_cpp(gcmN, dmN, cmN));
    return rcpp_result_gen;
END_RCPP
}
// BACKTRACK_cpp
List BACKTRACK_cpp(Rcpp::IntegerMatrix dm);
RcppExport SEXP _IncDTW_BACKTRACK_cpp(SEXP dmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dm(dmSEXP);
    rcpp_result_gen = Rcpp::wrap(BACKTRACK_cpp(dm));
    return rcpp_result_gen;
END_RCPP
}
// BACKTRACK2IN_cpp
List BACKTRACK2IN_cpp(Rcpp::IntegerMatrix dm, Rcpp::NumericMatrix diffM);
RcppExport SEXP _IncDTW_BACKTRACK2IN_cpp(SEXP dmSEXP, SEXP diffMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type diffM(diffMSEXP);
    rcpp_result_gen = Rcpp::wrap(BACKTRACK2IN_cpp(dm, diffM));
    return rcpp_result_gen;
END_RCPP
}
// BACKTRACK2II_cpp
List BACKTRACK2II_cpp(Rcpp::IntegerMatrix dm, Rcpp::IntegerMatrix diffM);
RcppExport SEXP _IncDTW_BACKTRACK2II_cpp(SEXP dmSEXP, SEXP diffMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dm(dmSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type diffM(diffMSEXP);
    rcpp_result_gen = Rcpp::wrap(BACKTRACK2II_cpp(dm, diffM));
    return rcpp_result_gen;
END_RCPP
}
