# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_dtw2vec <- function(x, y) {
    .Call(`_IncDTW_cpp_dtw2vec`, x, y)
}

cpp_dtw2vec_inc <- function(x, newObs, gcm_lc) {
    .Call(`_IncDTW_cpp_dtw2vec_inc`, x, newObs, gcm_lc)
}

cpp_dtw2vec_inc_ws <- function(x, newObs, gcm_lc, ws, ny) {
    .Call(`_IncDTW_cpp_dtw2vec_inc_ws`, x, newObs, gcm_lc, ws, ny)
}

cpp_dtw2vec_ws <- function(x, y, ws) {
    .Call(`_IncDTW_cpp_dtw2vec_ws`, x, y, ws)
}

cpp_dtw2vec_ea <- function(x, y, threshold) {
    .Call(`_IncDTW_cpp_dtw2vec_ea`, x, y, threshold)
}

cpp_dtw2vec_ws_ea <- function(x, y, ws, threshold) {
    .Call(`_IncDTW_cpp_dtw2vec_ws_ea`, x, y, ws, threshold)
}

cpp_dtw2vec_v32 <- function(x, y) {
    .Call(`_IncDTW_cpp_dtw2vec_v32`, x, y)
}

GCM_Sakoe_cpp <- function(cM, ws) {
    .Call(`_IncDTW_GCM_Sakoe_cpp`, cM, ws)
}

IGCM_Sakoe_cpp <- function(gcmN, dmN, cmN, ws) {
    .Call(`_IncDTW_IGCM_Sakoe_cpp`, gcmN, dmN, cmN, ws)
}

GCM_cpp <- function(cM) {
    .Call(`_IncDTW_GCM_cpp`, cM)
}

IGCM_cpp <- function(gcmN, dmN, cmN) {
    .Call(`_IncDTW_IGCM_cpp`, gcmN, dmN, cmN)
}

BACKTRACK_cpp <- function(dm) {
    .Call(`_IncDTW_BACKTRACK_cpp`, dm)
}

BACKTRACK2IN_cpp <- function(dm, diffM) {
    .Call(`_IncDTW_BACKTRACK2IN_cpp`, dm, diffM)
}

BACKTRACK2II_cpp <- function(dm, diffM) {
    .Call(`_IncDTW_BACKTRACK2II_cpp`, dm, diffM)
}

